-- DDL generated by Postico 1.4.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE if not exists provision (
   cluster text,
   vhost text,
   username text,
   password_enc text,
   billingcode text,
   tags jsonb,
   CONSTRAINT provision_pkey PRIMARY KEY (cluster, vhost)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX if not exists provision_pkey ON provision(cluster text_ops,vhost text_ops);